Generation 358   2024-03-26 00:25:35

diff --git a/rebuild b/rebuild
--- a/rebuild
+++ b/rebuild
@@ -37,7 +37,9 @@ fi
 echo $'\e[1m\e[96mnah, i\'d win\e[0m'
 
 # stop plasma making .gtkrc-2.0
-rm -f "$HOME/.gtkrc-2.0"
+if [[ -f ~/.gtkrc-2.0 ]]; then
+    mv "~/.gtkrc-2.0" "~/.gtkrc-2.0.bak"
+fi
 
 (
     set -o pipefail
@@ -50,7 +52,19 @@ rm -f "$HOME/.gtkrc-2.0"
         # initial rebuild (nom will be installed after this)
         sudo nixos-rebuild switch --flake '.#nixos' --impure
     fi
-)
+) || {
+
+    # restore .gtkrc-2.0
+    if [[ -f ~/.gtkrc-2.0.bak ]] && ! [[ -f ~/.gtkrc-2.0 ]]; then
+        mv "~/.gtkrc-2.0.bak" "~/.gtkrc-2.0"
+    fi
+    rm -f "~/.gtkrc-2.0.bak"
+
+    # exit on error
+    exit 1
+}
+
+rm -f "~/.gtkrc-2.0.bak"
 
 # commit
 gen=$(nix-env --list-generations | grep 'current' | sed 's/^[^0-9]*//' | sed 's/[^0-9]*$//')
