nixos-rebuild

diff --git a/rebuild b/rebuild
--- a/rebuild
+++ b/rebuild
@@ -5,8 +5,11 @@ alejandra . &>/dev/null
 git diff -U0 *.nix
 echo "nah, i'd win"
 logfile="rebuild.log"
-( sudo nixos-rebuild switch --flake .#nixos 2>&1 | grep -v "dirty$" | tee "$logfile" ) || (echo "An error occurred:" && cat "$logfile" | grep --color "error" && false )
-( home-manager switch --flake .#adaad@nixos 2>&1 | grep -v "dirty$" | tee "$logfile" ) || (echo "An error occurred:" && cat "$logfile" | grep --color "error" && false )
+(
+set -o pipefail
+( sudo nixos-rebuild switch --flake .#nixos 2>&1 | grep -v "dirty$" | tee "$logfile" ) || ( echo "An error occurred:" && cat "$logfile" | grep --color "error" && false )
+# ( home-manager switch --flake .#adaad@nixos 2>&1 | grep -v "dirty$" | tee "$logfile" ) || ( echo "An error occurred:" && cat "$logfile" | grep --color "error" && false )
+)
 git commit -am 'nixos-rebuild'
 echo "operation completed successfully :)"
 popd
